import type { DashboardSnapshot } from '@/shared/types'

const now = new Date()
const ago = (hours: number) => new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString()

export const mockSnapshot: DashboardSnapshot = {
  generatedAt: now.toISOString(),
  overview: {
    totalSessions: 128,
    backedUpSessions: 104,
    reclaimableBytes: 18_700_000_000,
    lastBackupAt: ago(3),
    totalTokens: 12_430_000,
    totalSizeBytes: 62_300_000_000,
    highRiskCleanupCount: 2,
  },
  agents: [
    { source: 'codex', name: 'Codex', installed: true, readable: true, rootPaths: ['~/.codex/sessions'], sessionCount: 46, sizeBytes: 14_200_000_000, lastScannedAt: ago(0.1) },
    { source: 'claude', name: 'Claude Code', installed: true, readable: true, rootPaths: ['~/.claude/projects'], sessionCount: 38, sizeBytes: 21_400_000_000, lastScannedAt: ago(0.1) },
    { source: 'cursor', name: 'Cursor', installed: true, readable: true, rootPaths: ['~/Library/Application Support/Cursor'], sessionCount: 22, sizeBytes: 9_700_000_000, lastScannedAt: ago(0.1) },
    { source: 'gemini', name: 'Gemini', installed: true, readable: true, rootPaths: ['~/.gemini'], sessionCount: 12, sizeBytes: 4_600_000_000, lastScannedAt: ago(0.1) },
    { source: 'opencode', name: 'OpenCode', installed: true, readable: true, rootPaths: ['~/.local/share/opencode'], sessionCount: 10, sizeBytes: 3_100_000_000, lastScannedAt: ago(0.1) },
  ],
  sessions: [
    {
      id: 'demo-codex-1',
      source: 'codex',
      title: 'Refactor auth flow',
      projectName: 'acme/web-app',
      projectPath: '/Users/demo/acme/web-app',
      branch: 'main',
      storagePath: '/demo/codex/auth.jsonl',
      storageKind: 'file',
      createdAt: ago(60),
      lastUpdated: ago(0.1),
      messageCount: 184,
      tokens: { input: 28_000, output: 16_200, cached: 4_000, total: 48_200, estimated: false },
      sizeBytes: 2_100_000,
      backupStatus: 'backed-up',
      tags: ['codex'],
      metadata: {},
    },
    {
      id: 'demo-claude-1',
      source: 'claude',
      title: 'Fix billing edge case',
      projectName: 'acme/billing',
      projectPath: '/Users/demo/acme/billing',
      branch: 'feature/fix-pricing',
      storagePath: '/demo/claude/billing.jsonl',
      storageKind: 'file',
      createdAt: ago(80),
      lastUpdated: ago(0.3),
      messageCount: 231,
      tokens: { input: 69_000, output: 31_700, cached: 12_000, total: 112_700, estimated: false },
      sizeBytes: 3_400_000,
      backupStatus: 'backed-up',
      tags: ['claude'],
      metadata: {},
    },
    {
      id: 'demo-cursor-1',
      source: 'cursor',
      title: 'Add analytics events',
      projectName: 'acme/analytics',
      projectPath: '/Users/demo/acme/analytics',
      branch: 'main',
      storagePath: '/demo/cursor/analytics.json',
      storageKind: 'file',
      createdAt: ago(90),
      lastUpdated: ago(1),
      messageCount: 92,
      tokens: { input: 19_000, output: 10_200, cached: 2_900, total: 32_100, estimated: true },
      sizeBytes: 1_200_000,
      backupStatus: 'backed-up',
      tags: ['cursor'],
      metadata: {},
    },
  ],
  cleanup: [
    {
      id: 'cleanup-1',
      kind: 'backed-up-session',
      title: 'Backed up sessions older than 30 days',
      source: 'codex',
      sessionIds: ['demo-codex-1'],
      paths: ['/demo/codex/auth.jsonl'],
      sizeBytes: 7_600_000_000,
      lastUpdated: ago(1000),
      reason: 'Already backed up and inactive for more than 30 days.',
      risk: 'low',
      recoverable: true,
      backedUp: true,
    },
    {
      id: 'cleanup-2',
      kind: 'large-log',
      title: 'Large Claude Code logs',
      source: 'claude',
      sessionIds: ['demo-claude-1'],
      paths: ['/demo/claude/billing.jsonl'],
      sizeBytes: 4_200_000_000,
      lastUpdated: ago(70),
      reason: 'Verbose logs safe to remove after backup.',
      risk: 'medium',
      recoverable: true,
      backedUp: false,
    },
    {
      id: 'cleanup-3',
      kind: 'duplicate-backup',
      title: 'Duplicate backup bundles',
      source: 'cursor',
      sessionIds: ['demo-cursor-1'],
      paths: ['/demo/backups/cursor'],
      sizeBytes: 3_100_000_000,
      lastUpdated: ago(200),
      reason: 'Multiple backups have identical session id and size.',
      risk: 'low',
      recoverable: true,
      backedUp: true,
    },
  ],
  backups: [],
  trash: [],
  usage: Array.from({ length: 30 }, (_, index) => {
    const date = new Date(now.getTime() - (29 - index) * 24 * 60 * 60 * 1000)
    const codex = 80_000 + Math.round(Math.sin(index / 2) * 25_000 + index * 1300)
    const claude = 70_000 + Math.round(Math.cos(index / 3) * 22_000 + index * 1000)
    const cursor = 35_000 + Math.round(Math.sin(index / 1.5) * 9_000)
    const gemini = 20_000 + Math.round(Math.cos(index / 2.2) * 8_000)
    const opencode = 16_000 + Math.round(Math.sin(index / 2.8) * 6_000)
    return {
      date: date.toISOString().slice(0, 10),
      codex,
      claude,
      cursor,
      gemini,
      opencode,
      total: codex + claude + cursor + gemini + opencode,
    }
  }),
  storage: [
    { source: 'claude', label: 'Claude Code', sizeBytes: 21_400_000_000, sessions: 38 },
    { source: 'codex', label: 'Codex', sizeBytes: 14_200_000_000, sessions: 46 },
    { source: 'cursor', label: 'Cursor', sizeBytes: 9_700_000_000, sessions: 22 },
    { source: 'gemini', label: 'Gemini', sizeBytes: 4_600_000_000, sessions: 12 },
    { source: 'opencode', label: 'OpenCode', sizeBytes: 3_100_000_000, sessions: 10 },
  ],
}
